/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as LeerlijnRouteImport } from './routes/leerlijn'
import { Route as SpeelRouteImport } from './routes/speel'
import { Route as WerkstroomRouteImport } from './routes/werkstroom'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const LeerlijnRoute = LeerlijnRouteImport.update({
  id: '/leerlijn',
  path: '/leerlijn',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeelRoute = SpeelRouteImport.update({
  id: '/speel',
  path: '/speel',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkstroomRoute = WerkstroomRouteImport.update({
  id: '/werkstroom',
  path: '/werkstroom',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/leerlijn': typeof LeerlijnRoute
  '/speel': typeof SpeelRoute
  '/werkstroom': typeof WerkstroomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/leerlijn': typeof LeerlijnRoute
  '/speel': typeof SpeelRoute
  '/werkstroom': typeof WerkstroomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/leerlijn': typeof LeerlijnRoute
  '/speel': typeof SpeelRoute
  '/werkstroom': typeof WerkstroomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atelier' | '/leerlijn' | '/speel' | '/werkstroom'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atelier' | '/leerlijn' | '/speel' | '/werkstroom'
  id: '__root__' | '/' | '/atelier' | '/leerlijn' | '/speel' | '/werkstroom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  LeerlijnRoute: typeof LeerlijnRoute
  SpeelRoute: typeof SpeelRoute
  WerkstroomRoute: typeof WerkstroomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leerlijn': {
      id: '/leerlijn'
      path: '/leerlijn'
      fullPath: '/leerlijn'
      preLoaderRoute: typeof LeerlijnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speel': {
      id: '/speel'
      path: '/speel'
      fullPath: '/speel'
      preLoaderRoute: typeof SpeelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkstroom': {
      id: '/werkstroom'
      path: '/werkstroom'
      fullPath: '/werkstroom'
      preLoaderRoute: typeof WerkstroomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  LeerlijnRoute: LeerlijnRoute,
  SpeelRoute: SpeelRoute,
  WerkstroomRoute: WerkstroomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
